#given this family hash, print out the name, age and gender of each family member:

munsters = {
  "Herman" => { "age" => 32, "gender" => "male" },
  "Lily" => { "age" => 30, "gender" => "female" },
  "Grandpa" => { "age" => 402, "gender" => "male" },
  "Eddie" => { "age" => 10, "gender" => "male" },
  "Marilyn" => { "age" => 23, "gender" => "female"}
}

munsters.each { |name, detail|
  puts "#{name} is a #{detail['age']}-year-old #{detail['gender']}."
}

#parse through each hash
#attach key of "name" "age" and "gender" to string to print out